spring:
  application:
    name: ai-agent-project
  profiles:
    active: local
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ai-agent-project}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

    pgvector:
      url: ${PG_URL:jdbc:postgresql://pgm-bp109o1f2pb4f79qmo.rwlb.rds.aliyuncs.com:5432/sheng_ai_agent}
      username: ${PG_USERNAME:my_user01}
      password: ${PG_PASSWORD:}
      driver-class-name: org.postgresql.Driver
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yusheng.aiagentproject.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

ai:
  guardrail:
    forbidden-words:
      - 违禁词
      - 敏感词

searchapi:
  api-key: ${SEARCHAPI_API_KEY:}
